### PR TITLE
Fixed issue #10

### PR DESCRIPTION
**Pull request by nisan-abeywickrama**
Added blue themed index.html

### CODE REVIEW

**Comment by nisan-abeywickrama** [comment]
This is how the index.html page looks like. 
chatApp

**Comment by CeesJol** [comment]
Looks so sick...

Could you change the PR from master to dev? (CeesJol:dev) I want to tweak the responsiveness a bit

I will merge it into master later

**Comment by nisan-abeywickrama** [comment]
Okay

**Comment by CeesJol** [comment]
👍

**Pull request merged**
